import 'package:flutter/material.dart';

const Color kBlackColor = Color(0xFF100E23);
const Color kSeconderyPurbleColor = Color(0xffE5CAFF);
const Color kSeconderyGreenColor = Color(0xffB5EDD4);
const Color kSeconderyBlueColor = Color(0xffD3F5FF);
const Color kSeconderyPinkColor = Color(0xffFFC2AF);
const Color kPrimaryPurbleColor = Color(0xff62249F);
const Color kPrimaryGreenColor = Color(0xff097947);
const Color kPrimaryBlueColor = Color(0xff01536B);
const Color kSeconderyRedColor = Color(0xff712911);
const kPrimaryColor = Color(0xFF0D6DFD);
const kPrimarytextColor = Color(0xFF100E23);
Color kSeconderyOrangeColor = const Color(0xffE23632);
Color kWhiteColor = const Color(0xffF0Eff5);
Color kPinkColor = const Color(0xFFFAD3D9);
Color kGreyColor = const Color(0xFF9E9E9E);
Color kPrimaryRedColor = const Color(0xffc92120);
Color kTextFieldColor = const Color(0xFF2C2441);
const Color backgroundScaffoldColor = Color(0xFFF2F2F2);
