// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACEZXSDHP34gdKeLc5zLwLzEkgHKVNv18',
    appId: '1:443910820495:web:4c337baf9bf913b19916fa',
    messagingSenderId: '443910820495',
    projectId: 'egy-explor',
    authDomain: 'egy-explor.firebaseapp.com',
    storageBucket: 'egy-explor.appspot.com',
    measurementId: 'G-DC6D8WR9DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuMfyKmBC0gR8UN4KfCwYmurxiUffOnV8',
    appId: '1:443910820495:android:a1c310bfbd80e3019916fa',
    messagingSenderId: '443910820495',
    projectId: 'egy-explor',
    storageBucket: 'egy-explor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC37hpqlYgbFf0DmXNRLERZ7jRzjbNtDJo',
    appId: '1:443910820495:ios:8500bf378e0b4a999916fa',
    messagingSenderId: '443910820495',
    projectId: 'egy-explor',
    storageBucket: 'egy-explor.appspot.com',
    iosBundleId: 'com.example.egyExlpor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC37hpqlYgbFf0DmXNRLERZ7jRzjbNtDJo',
    appId: '1:443910820495:ios:79bfdb7927a26fdf9916fa',
    messagingSenderId: '443910820495',
    projectId: 'egy-explor',
    storageBucket: 'egy-explor.appspot.com',
    iosBundleId: 'com.example.egyExlpor.RunnerTests',
  );
}
